server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER


  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aryan-1121/hotel-rating-config-server.git
          clone-on-start: true